version: "3.9"

services:
  web:
    build: .
    command: >
      bash -c "cd backend && gunicorn core.asgi:application
      -k uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:8000"
    volumes: ["./backend:/app/backend"]
    ports: ["8000:8000"]
    env_file: [.env]
    depends_on: [db, redis]

  worker:
    build: .
    command: >
      bash -c "cd backend && celery -A core worker -l info
      -Q default,ingest,analyze,email
      --concurrency=6
      --prefetch-multiplier=1"
    volumes: ["./backend:/app/backend"]
    env_file: [.env]
    depends_on: [db, redis]

  beat:
    build: .
    command: bash -c "cd backend && celery -A core beat -l info --pidfile= --schedule=/tmp/celerybeat-schedule.db"
    volumes: ["./backend:/app/backend"]
    env_file: [.env]
    depends_on: [db, redis]

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: threadiq
      POSTGRES_USER: threadiq
      POSTGRES_PASSWORD: threadiq
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]