alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED

envs:
- key: CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: CELERY_BROKER_CONNECTION_MAX_RETRIES
  scope: RUN_AND_BUILD_TIME
  value: "10"

features:
- buildpack-stack=ubuntu-22

ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: "/"

name: threadiq-macro-insights-prod
region: nyc

services:
- http_port: 8080
  image:
    registry: threadiq
    registry_credentials: EV[1:sJBqc81XZsVoESF26Ein/GyFOKExfe0i:sWdFC45bE2vmIlgZ/lIt1y3pZfDexceUkliYh5hIVg2u4wrYtaR128gyu3FXqyCorDE1uBK22cnOj7Dgr3s8hQ==]
    registry_type: GHCR
    repository: threadiq-macro-insights
    tag: main
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: web
  run_command: bash -c "cd backend && gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080"

workers:
# Worker service
- image:
    registry: threadiq
    registry_credentials: EV[1:sJBqc81XZsVoESF26Ein/GyFOKExfe0i:sWdFC45bE2vmIlgZ/lIt1y3pZfDexceUkliYh5hIVg2u4wrYtaR128gyu3FXqyCorDE1uBK22cnOj7Dgr3s8hQ==]
    registry_type: GHCR
    repository: threadiq-macro-insights
    tag: main
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: worker
  run_command: bash -c "cd backend && echo REDIS_URL=$REDIS_URL && celery -A core worker -l debug -Q default,ingest,analyze,email --autoscale=12,2 --without-heartbeat"

# Beat service
- image:
    registry: threadiq
    registry_credentials: EV[1:sJBqc81XZsVoESF26Ein/GyFOKExfe0i:sWdFC45bE2vmIlgZ/lIt1y3pZfDexceUkliYh5hIVg2u4wrYtaR128gyu3FXqyCorDE1uBK22cnOj7Dgr3s8hQ==]
    registry_type: GHCR
    repository: threadiq-macro-insights
    tag: main
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: beat
  run_command: bash -c "cd backend && celery -A core beat -l info --pidfile= --schedule=/tmp/celerybeat-schedule.db"
