name: Docker Build and Deploy (GHCR → DigitalOcean App Platform)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: threadiq-macro-insights-prod
      IMAGE: ghcr.io/threadiq/threadiq-macro-insights

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:pr
            ${{ env.IMAGE }}:main
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Render DO App Spec from template
        run: |
          mkdir -p .do
          export PGPASSWORD='${{ secrets.PGPASSWORD }}'
          export REDIS_URL='${{ secrets.REDIS_URL }}'
          export SECRET_KEY='${{ secrets.SECRET_KEY }}'
          export WEAVIATE_API_KEY='${{ secrets.WEAVIATE_API_KEY }}'
          envsubst < .do/app.tmpl.yaml > .do/app.yaml

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          app-name: threadiq-macro-insights-prod
          images: |
            web=${{ env.IMAGE }}:main
            worker=${{ env.IMAGE }}:main
            beat=${{ env.IMAGE }}:main
          spec: .do/app.yaml