name: Docker Build and Deploy (GHCR → DigitalOcean App Platform)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: threadiq-macro-insights-prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:pr
          # optional: cache
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # IMPORTANT: DigitalOcean must be able to pull this image.
      # Ensure the GHCR package visibility is PUBLIC (in repo → Packages → settings),
      # OR use DO App build from GitHub instead of images, OR switch to DOCR.

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app-action@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          app-name: threadiq-macro-insights-prod
          images: |
            web=${{ env.IMAGE }}
            worker=${{ env.IMAGE }}
            beat=${{ env.IMAGE }}